<?php
/**
 * BULIG — Level 4 (Reading Fluency) passage content, Grades 1-6.
 * Single source of truth for both the pupil-facing quest map
 * (pupil/level4.php passes this to js/level4.js as JSON) and the
 * teacher fluency-scoring form (teacher/progress.php), so the exact
 * same passage text/word counts are used in both places.
 *
 * Transcribed directly from the six LEVEL-4-FLUENCY-GRADE-*.pdf module
 * booklets. Every grade's Pre-test, intervention (practice), and
 * Post-test passages are included exactly as titled in that grade's
 * own Table of Contents and in the same order.
 *
 * word_count is the module's own printed "Number of Words in the
 * Passage" figure (recomputed only where noted below) — used as-is
 * for the Oral Reading Score / WPM formulas in
 * config/level4_helpers.php, exactly as the paper module defines them.
 *
 * KNOWN SOURCE-DOCUMENT DISCREPANCIES (not skipped on our end —
 * this reflects what's actually printed in the module, or a
 * PDF-extraction artifact that was corrected against the page image
 * or, for public-domain works, the well-known original text):
 *   - Grade 3's own TOC separates "Amusement Park Problem II" and
 *     "The Generosity of Rantideva" as two activities; a table-header
 *     rendering glitch on that one page ran their scoring tables
 *     together in the raw PDF text, but both are included here in
 *     full as two separate passages, matching the TOC.
 *   - Grade 4's own TOC lists a "Songs of the Witches II", but the
 *     page that should hold it is a misprinted duplicate of the
 *     'My First Baseball Game' continuation elsewhere in the same
 *     booklet — there is no distinct 'Songs of the Witches II' text
 *     anywhere in the source PDF, so (matching how the Level 2B
 *     module's own TOC/Activity-23 typo was handled previously) it is
 *     not invented here; Grade 4 ships the 9 intervention passages
 *     that actually exist.
 *   - Grade 3's "A Robot Dog" and Grade 1's "The Cat" (pre-/post-test)
 *     each had their opening sentence lost to a stylized title/cover
 *     graphic that has no text layer; restored from the page image.
 *   - Grade 3's "I Am" (John Clare, 1848, public domain) and Grade
 *     5's "Old MacDonald Had a Farm" (traditional, public domain)
 *     were printed across a multi-column layout that the PDF's text
 *     layer stores out of reading order; both were restored to their
 *     correct, well-known original wording rather than kept scrambled,
 *     since a jumbled passage would actively work against a reading-
 *     fluency exercise. word_count reflects the corrected text.
 */
declare(strict_types=1);

function bulig_level4_content(): array
{
    return [
        1 => [
            'pretest' => ['title' => 'The Cat', 'word_count' => 27, 'text' => 'The cat is small and white. It likes to sleep on the mat. The cat plays with a ball. It runs fast in the yard.'],
            'interventions' => [
                ['title' => 'My Dog', 'word_count' => 25, 'text' => 'I have a brown dog. It likes to run and jump. The dog wags its tail. I play with my dog every day.'],
                ['title' => 'The Sun', 'word_count' => 24, 'text' => 'The sun is bright. It shines in the sky. The sun makes the flowers grow. I like to play under the sun.'],
                ['title' => 'My Hat', 'word_count' => 26, 'text' => 'I wear it when I go outside. The hat is soft and warm. My sister likes my hat too.'],
                ['title' => 'The Bird', 'word_count' => 25, 'text' => 'A small bird sits on a tree. It sings a happy song. The bird flies in the sky. I watch it every morning.'],
                ['title' => 'Rainy Day', 'word_count' => 24, 'text' => 'I wear my yellow raincoat. I jump in the puddles. The rain is fun and makes me happy.'],
                ['title' => 'The Market', 'word_count' => 30, 'text' => 'We buy apples and bread. I see a small cat near the stand. I enjoy visiting the market every week.'],
                ['title' => 'Tim\'s Ball', 'word_count' => 25, 'text' => 'Tim has a red ball. He throws it to his friend. The ball rolls on the grass. They laugh and run after it.'],
                ['title' => 'The Dog and Cat', 'word_count' => 26, 'text' => 'The dog sees a cat. The cat runs under the tree. The dog stops and watches. They sit in the sun together.'],
                ['title' => 'My Family', 'word_count' => 23, 'text' => 'I have a mom and dad. I have a little sister too. We eat lunch together. We play games and laugh.'],
                ['title' => 'My School', 'word_count' => 29, 'text' => 'I go to school every day. I see my friends in class. We read books and write in our notebook. School is fun and I like it.'],
            ],
            'posttest' => ['title' => 'The Cat', 'word_count' => 27, 'text' => 'The cat is small and white. It likes to sleep on the mat. The cat plays with a ball. It runs fast in the yard.'],
        ],
        2 => [
            'pretest' => ['title' => 'The Picnic', 'word_count' => 47, 'text' => 'We bring sandwiches, fruits, and juice to eat. We sit on a blanket under a big tree. We play games and listen to birds singing. The picnic is fun and exciting for everyone in the class.'],
            'interventions' => [
                ['title' => 'The Farm', 'word_count' => 45, 'text' => 'The farmer feeds the animals every morning. The cows drink water, and the chickens peck at the grains. The pigs roll in the mud happily. The farm is busy and full of life all day long.'],
                ['title' => 'The Birthday Party', 'word_count' => 41, 'text' => 'I have balloons, a cake, and gifts. My friends come to celebrate with me. We play games, sing songs, and eat cake together. It is the best birthday party I have ever had.'],
                ['title' => 'My School Bag', 'word_count' => 41, 'text' => 'It has books, pencils, and my lunchbox inside. I carry it to school every morning. I keep it neat and clean. My school bag helps me bring all my school things easily.'],
                ['title' => 'The Zoo', 'word_count' => 41, 'text' => 'We see lions, elephants, and monkeys. The monkeys swing from the trees. The elephants splash water with their trunks. The zoo is fun, and I learn many new things about animals.'],
                ['title' => 'The Beach', 'word_count' => 43, 'text' => 'We go to the beach on a sunny day. The sand is soft, and the waves are small. I build a sandcastle with my friends. We collect shells and play near the water. The beach is fun and exciting every summer.'],
                ['title' => 'My Bike', 'word_count' => 41, 'text' => 'I ride it around the yard every day. I pedal fast and sometimes ring the bell. My friends ride with me too. Riding my bike is fun and makes me happy and strong.'],
                ['title' => 'The Train', 'word_count' => 42, 'text' => 'The train is long and blue. It moves fast on the tracks. The passengers sit and look out of the windows. The train goes to many cities and towns. Riding the train is fun and exciting for children and adults.'],
                ['title' => 'The Library', 'word_count' => 45, 'text' => 'I go to the library to read books. There are many storybooks and picture books. I sit quietly and enjoy reading every day. The librarian helps me find the books I like. The library is a nice place to learn and have fun.'],
                ['title' => 'The Raincoat', 'word_count' => 40, 'text' => 'I wear my yellow raincoat and boots. I jump in the puddles and splash the water. The rain falls softly on the roof. Wearing my raincoat makes me happy and dry in the rain.'],
                ['title' => 'The Bakery', 'word_count' => 42, 'text' => 'There are cakes, bread, and cookies on the shelves. The smell is sweet and nice. I buy a small cake for my snack. The bakery is full of yummy food that I enjoy.'],
            ],
            'posttest' => ['title' => 'The Picnic', 'word_count' => 47, 'text' => 'Post-test Passage We bring sandwiches, fruits, and juice to eat. We sit on a blanket under a big tree. We play games and listen to birds singing. The picnic is fun and exciting for everyone in the class.'],
        ],
        3 => [
            'pretest' => ['title' => 'The Ant and the Fly', 'word_count' => 199, 'text' => 'Aesop Fable Once, an Ant and a Fly were fighting over who was more important. The Fly said, “Ant! What do you think you are? How can you even think about comparing yourself to me? Look at me! You have to work hard but I pass my time with the rich and the learned. I fly into the temples and taste the offerings. I can sit on the King’s crown and kiss the Queen’s forehead. I do not work, yet have the best life!” The Ant replied, “Don’t be so proud! You are always hated when you enter the temples. You are driven away as soon as you sit on the King’s crown or the Queen’s forehead. You do not have anything left for the difficult times as you are lazy. In winters, you feed yourself on a pile of cow dung. Look at me! I work hard and gather a store of grain for the winter. Later on, when you shiver in the cold, I am safe and at peace in my cozy home. I am prepared to live in any season of the year.” Look at your own faults, before finding faults in others.'],
            'interventions' => [
                ['title' => 'Max\'s Good Habit', 'word_count' => 209, 'text' => 'Henry Joyce Max reads more than anyone he knows. He loves to read during all of his free time. His friends tease him because he would rather read than play video games, but his parents and his teachers are proud of him. They say reading is important, and it will help him learn about the world around him. They al-so tell him it is a good habit to read on a regular basis. One day Max was reading a magazine article quizizz-media/quizzes/e8bec76a-3ecd- 4a1e-93f7-b6a07b9b61b5 friends all about volcanoes and what causes them to erupt. The very next week, his his class was assigned a science project about volcanoes. Guess who everyone wanted in their project group? Max’s friends weren’t teasing him anymore. Max ended up being in a group with Liz, Anna and Josh. The assignment was to create a poster board with information about volcanoes and to build a volcano model. Max made copies of the magazine article about volcanoes so his project partners could read about them too. They also went to the library to look for more information about volcanoes. The group met at Anna’s house that night to organize the information and decide what they'],
                ['title' => 'Max\'s Good Habit II', 'word_count' => 189, 'text' => 'They all asked Max what he thought was most important. Then they decided on the following together. Max reads more than anyone he knows. What causes volcanoes to erupt? The release of pressure when mag-ma rises up through cracks in the Earth’s crust causes volcanoes to erupt. How do volcanoes form? Lava from eruptions cools and forms new crust. The crust builds up after several eruptions to form a volcano. How hot is lava? Lava can get as hot as 1,165 Fahrenheit. The house to build their volcano. They used cardboard and modeling clay. First, they made a volcano shape with the cardboard, and then they covered the shape in brown and red clay. The red was lava flowing down the v o l c a n o . They a l s o a t - tached red clay to the top of the volcano to make it look like it was erupting. The volcano looked great. Max, Liz, Anna and Josh were very proud of their hard work. When they turned in their project, their teacher was proud too. Thanks to Max’s good habit, they earned an A+ on both parts of the project. AI-generated digital illustration, 2026. Created using an AI image file:///C:/Users/user/ Downloads/3rd-grade-3-readingmax-good-habit.pdf'],
                ['title' => 'Amusement Park Problem', 'word_count' => 177, 'text' => 'The smell of popcorn was in the air. I could hear kids laughing and screaming. People were everywhere! The breeze felt warm on my skin. It was a perfect day at the amusement park. My family and I wandered around the park, getting snacks and going on rides. I loved almost all types of rides! I loved to go fast and to spin around, to go down hills and to get splashed. The only rides I didn’t like were rides that turn you upsidedown. My little brother, Ben, didn’t like those either, but my older sister, Laura, loved them. When we finally were near a ride that went upside-down, she started asking me to go with her. I told her I don’t like those rides, but she kept character-show-sitting-ball-isolated- Then she started whining because she didn’t want to go alone. I was feeling sympathy for her, so I started thinking that maybe I should go with her, even though I really don’t like to go upside-down. I looked to my parents for help. amusement-park-vector-graphics-royalty-free-illust-'],
                ['title' => 'Amusement Park Problem II', 'word_count' => 234, 'text' => '“Matt, you are allowed to stand up for yourself. If something makes you feel rally uncomfortable, you can tell people ‘no.’ It’s OK to tell Laura that you love her, but that you can’t go with her because going upside-down makes you uncomfortable. Be strong but kind when you tell her, so that she knows you’re serious,” Mom said. “I don’t want to make Laura mad or sad, though,” I replied to Mom, “and I don’t want her to think I’m being mean.” “There’s a difference between being aggressive and being assertive. You’re not saying ‘no’ to be mean to Laura or to hurt her feelings, you’re just listening to your own feelings to make sure you stay safe. It’s fine to tell her no for this,” Mom answered. “The same goes for Laura. If you ask her to arm wrestle and she doesn’t feel comfortable, she’s allowed to say ‘no,’ too. We are all allowed to stand up for ourselves to make sure we stay safe. Does that make sense?” previews/007/098/140/original/cartoon-funny-circusher, but that I wasn’t comfort-able going on upside-down rides today because they scare me. She was sad, but went on the ride by herself and was really happy when it was over. We had a great rest of the day at the amusement park! comprehension-worksheets/third-grade-3/ 863768_photos-park-clipart-png-png-images- Typ s o f Mis- Mispronun- Omis- Substi- Inser- Repe- Transpo- Rever- Total amusement-pa r k.p n g cues ciation sion tution tion tition sition sal Number of Miscues Number of Words in the Passage 234 Oral Reading Score = 234 ________/ 234 X 100 Reading Level (Ind-98-100, Ins-90-96, Frus– 89 below) Reading Speed = Words Read/Reading time in seconds X 60 words per Minute'],
                ['title' => 'The Generosity of Rantideva', 'word_count' => 174, 'text' => 'Rantideva was born in a rich family. Even as a child, he would share his riches with the needy. He got married and had sons. With no thought for the future, Rantideva and his wife continued to be generous. No one went away from their home empty-handed. Ultimately, Rantideva ran out of money. His family had to go without food for months. One day, Rantideva managed to get some rice, ghee, wheat and sugar. Just then a holy man knocked at their door. Rantideva received the guest by bowing to him and served food to him. The holy man went away satisfied. Half of the food was still left for Rantideva and his family. As they sat down to eat, a hungry farmer came looking for food. Rantideva offered him a seat, made him comfortable, and served him food. The farmer enjoyed his meal. There was still some food left. Rantideva’s family decided to share whatever had remained. As they sat down to eat, a traveler appeared at the door.'],
                ['title' => '"I Am"', 'word_count' => 137, 'text' => 'I am—yet what I am none cares or knows; My friends forsake me like a memory lost; I am the self-consumer of my woes— They rise and vanish in oblivious host, Like shades in love and death\'s oblivion lost; And yet I am, and live—like vapours tossed Into the nothingness of scorn and noise, Into the living sea of waking dreams, Where there is neither sense of life or joys, But the vast shipwreck of my life\'s esteems; Even the dearest that I loved the best Are strange—nay, rather, stranger than the rest. I long for scenes where man hath never trod, A place where woman never smiled or wept; There to abide with my Creator, God, And sleep as I in childhood, sweetly slept: Untroubling and untroubled where I lie, The grass below—above the vaulted sky.'],
                ['title' => 'Verb To Be', 'word_count' => 98, 'text' => 'James Hampshire am Whole world You are They will be amazed He is third person Yeah She is I am It is You are We are awesome He is third Person You are She is They are It is subject pronouns We are awesome With the verb to be You are I am a teacher They are And subject pronouns You are the student With the verb to be He is a Doctor Well this is the And Verb to be She is intelligent And my friend This is the future You\'re on your way That we\'re building Here today'],
                ['title' => 'Verb To Be II', 'word_count' => 123, 'text' => 'It\'s easy as One two three Subject (pronoun) Subject (pronoun) Just practice When I say verb to Everyday You say be This is the future Verb to (Be) That we\'re building Here today Verb to (Be) You\'ll show the This is the future Whole world That we\'re building They will be amazed Here today You\'ll show the Yeah I am Whole world You are They will be amazed He is third person I am She is You are He is third person It is She is We are awesome It is You are We are awesome They are You are subject pronouns They are With the verb to be subject pronouns When I say subject You say pronoun With the verb to be'],
                ['title' => 'Daisies', 'word_count' => 80, 'text' => 'Daisies by Frank Dempster Sherman At evening when I go to bed I see the stars shine overhead; They are the little daisies white That dot the meadow of the Night. And often while I\'m dreaming so, Across the sky the Moon will go; It is a lady, sweet and fair, Who comes to gather daisies there. For, when at morning I arise, There\'s not a star left in the skies; She picked them all and dropped them down Into the meadows of the town.'],
                ['title' => 'A Robot Dog', 'word_count' => 403, 'text' => 'A Robot Dog walked and walked. After a little bit, they walked past a big tree. Poof! Rocky was a robot dog. “Woof, woof,” barked Rocky the robot dog. “What is going on?” asked Andrew. “Who turned my dog into a robot dog?” Andrew looked all around him. He looked up the street. He looked down the street. He looked behind the tree. He looked up into the tree. No one was there. He stopped and stood still. “Hee, hee, hee,” he heard. It came from the tree. “Woof, woof,” barked Rocky the robot dog at the tree. Andrew looked at the tree. He could not see anything different about this tree. He could not think of what to do. “Tree, are you a real tree?” asked Andrew. The tree did not say anything. Rocky the robot dog came over and smelled the tree. “Woof, woof,” he barked at it again. Andrew was mad. He did not like it that Rocky was a robot dog. Andrew walked over to the tree and tickled it. “Stop that,” said the tree. “Why did you tickle me?” “I think you turned my dog into a robot dog,” said Andrew. “Maybe I did, and maybe I didn’t,” said the tree who was holding his branches in front of himself so Andrew could not tickle him again. “It is kind of funny to see a dog become a robot.” Andrew got real mad this time and went up to the tree. He pushed away the tree’s branches and tickled him some more. “Oh, stop, stop,” said the tree. “I don’t want to be tickled anymore.” “I still think you turned Rocky into a robot dog,” said Andrew who was about to tickle the tree again. “Okay, okay,” said the tree. “I turned your dog into a robot dog. Just don’t tickle me anymore.” “Well, I don’t think it is funny,” said Andrew. “Now turn Rocky the robot dog back into Rocky the real dog.” “Okay,” said the tree. Poof! Rocky was Rocky the real dog again. “Now don’t do that anymore,” said Andrew. “Someone might get mad and tickle you again. You would not like that.” “Okay, I won’t turn dogs into robot dogs anymore,” said the tree. Andrew and Rocky walked home. The tree never turned any more dogs into robots, but every now and then, Andrew would see a robot butterfly go flying past his home. dog'],
            ],
            'posttest' => ['title' => 'The Ant and the Fly', 'word_count' => 199, 'text' => 'Aesop Fable Once, an Ant and a Fly were fighting over who was more important. The Fly said, “Ant! What do you think you are? How can you even think about comparing yourself to me? Look at me! You have to work hard but I pass my time with the rich and the learned. I fly into the temples and taste the offerings. I can sit on the King’s crown and kiss the Queen’s forehead. I do not work, yet have the best life!” The Ant replied, “Don’t be so proud! You are always hated when you enter the temples. You are driven away as soon as you sit on the King’s crown or the Queen’s forehead. You do not have anything left for the difficult times as you are lazy. In winters, you feed yourself on a pile of cow dung. Look at me! I work hard and gather a store of grain for the winter. Later on, when you shiver in the cold, I am safe and at peace in my cozy home. I am prepared to live in any season of the year.” Look at your own faults, before finding faults in others.'],
        ],
        4 => [
            'pretest' => ['title' => 'My First Baseball Game', 'word_count' => 255, 'text' => 'Randy Ryan I remember my first Cubs game. My uncle came to take my sister and me to it. It was a sunny Saturday. He drove all the way from Indiana to get us. Then we took the train to the ballpark. He said it would be hard to find a parking space there, so he didn’t drive there. He was right. When we got there it was so crowded. We had tickets that were for seats far back. It seemed like I climbed about 300 steps to get to them. But when we got there and I turned around I could see everything. I saw the whole field. It was much better than watching it on TV. Then the game started. Everyone cheered. The man next to me said, “This is going to be the year. They are playing really well.” My uncle said to him, “Let’s hope this is the one.” But then he whispered to us, “Jerome and Felicia, we’ll have to wait and see. Remember last year? They started out well and then they lost at the end.” “Hey, Hey, Hey!” The Cub batter hit a ball far to the wall. Just then I heard “Hot dogs!” “Peanuts!” I looked and saw a man with a big tray hanging from his shoulders. It was full of hotdogs in plastic wrap and bags of peanuts. “Three hot dogs,” my uncle shouted. Then he gave the man next to us $6. He passed it to the man with the hot dogs. He sent back three hot dogs. “This is great,” I said to my uncle. “Not so great,” he said. “We just struck out.” While I had been watching the hotdogs, the team had struck out. It went on that way for the rest of the game. We got peanuts. We even got another hot dog. And the Cubs kept losing. We’d all hope every time a batter came to bat. One by one they struck out. Still, everyone was staying happy. Even at the end. The score was 7 to 0. The Cubs never got a run. “Tomorrow, they’ll win,” one person said. “Right. This was just a bad day for them,” another said. “The pitcher tomorrow is really good.” When we were on the way home, I asked my uncle, “Why was everyone so sure they will win next time?” “That’s what it means to be a Cubs fan. We believe in tomorrow. When they win, it’s the best. Every year, we hope. Every game we hope. That’s loyalty. It’s about supporting your team no matter what. Cubs fans are loyal. And it’s about having fun as a family. Did you have fun?” As our uncle was about to drive home to Indiana, Felicia said, “It was great. I see what you meant. Even when they lose, they are like a family, they stick together. Thanks for taking us. And thanks for being loyal to us.”'],
            'interventions' => [
                ['title' => 'The Singing Plant', 'word_count' => 209, 'text' => 'Todd awoke to singing. The singing was light and airy. It reminded him of a sunrise. Well that’s appropriate, thought Todd, it’s so early the sun is probably just rising. As his mind grew more awake, Todd realized that he didn’t know where the music was coming from. He checked his radio, as well as his phone. Nothing. He stretched and looked around his room. Nothing in here would be singing, he thought. Todd got out of bed and walked toward his window, thinking that maybe one of his neighbors was playing music. The music didn’t get louder as he walked toward the window, and when he opened the window he could tel l that the music did not come from outside. Todd walked toward his bedroom door, but was hesitant to go out into the hallway. It was still pretty dark, and the rest of his family was still asleep. That always made him nervous to leave his room. It’s only singing, though, there’s nothing scary about that, Todd thought. He opened the door, and could hear the music coming from downstairs. He walked downstairs and followed the music into the kitchen. There, he found the source of the music, but he couldn’t believe his eyes!'],
                ['title' => 'The Singing Plant II', 'word_count' => 195, 'text' => 'The Singing Plant The plants on the windowsill above the sink were singing! Singing plants! How is this possible? There were 3 of them, all gently swaying and singing together. Todd sat and watched them for a while, trying to understand how and why the plants had all of a sudden become musical plants. Their song faded away after a few minutes, and the plants became still. Todd stayed to watch, just in case they started singing again. His Dad found him sitting in the kitchen watching the plants. “What’s going on, Todd?” his dad asked. “What kind of plant are these?” Todd asked in return. “They’re just little houseplants, they won’t grow too much bigger than they are now. Why?” “They were singing. I didn’t know plants could sing!” exclaimed Todd. “Todd, plants don’t sing. Were you dreaming?” Dad asked, concerned. “No, really, they were! That’s what woke me up this morning!” “Hmmm…” Dad sighed. He walked over to the sink, grabbed a cup, and began to water the plants. He jumped back in surprise when the flowers started singing a happy little tune! “Holy cow! They must have been thirsty! I’ve never seen anything like this!”'],
                ['title' => 'A Glass of Cold Water', 'word_count' => 258, 'text' => 'Everybody calls me young, beautiful, wonderful. Am I? Look at my hair, my lips, my red rosy cheeks and a pair of blinkering eyes. I remember, somebody says that I look like my mother that I look like my mother. But that when she was young. Now, I am much lovelier than she is. I’m a mortal Venus. Oops! What time is it? I must get ready for the party! Beep-beep…!A-huh! Here they are! Yes, I’m coming! “Child, are you still there?”“Hmp! That’s my mama” “Child, are you still there? Will you please get me a glass of cold water?” “Mama, I’m in a hurry!” “Please child, try to get me a glass of cold water.” “Mama, please, try to get it on your own.” “Please child, try to get me a glass of cold water!”At the party, I danced and danced the whole night. You see, I can’t leave the party at once. I have to dance with everybody who proposed to me. At last, the party is over. I’m very tired. Very, very tired. So, I went home to tell mama what happened. “Mama, I’m home! It’s very quiet. “Mama, I’m home!” Nobody answers. Where is she? I look for her in the sala, but she’s not there. Where is she? A-huh! In the kitchen! I saw my mama, lying down on the floor, dead. With a glass on her hand. I remember, she tried to get it. Oh, God, just for the glass of cold water! Mama! Ma-'],
                ['title' => 'The Elephant and the Crocodile', 'word_count' => 379, 'text' => 'An Elephant and a Crocodile were once standing beside a river. They were disputing as to which was the better animal. “Look at my strength,” said the Elephant. “I can tear up a tree, roots and all, with my trunk.” “Ah! but quantity is not quality, and your skin is not nearly so tough as mine,” replied the Crocodile, “for neither spear, arrow, nor sword can pierce it.” Just as they were coming to blows, a Lion happened to pass. “Heyday, sirs!” said His Majesty, going up to them, “let me know the cause of your quarrel.” “Will you kindly tell us which is the better animal?” cried both at once. “Certainly,” said the Lion. “Do you see that soldier’s steel helmet on yonder wall?” pointing at the same time across the river. “Yes!” replied the beasts. “Well, then,” continued the Lion, “go and fetch it, and bring it to me, and I shall be able then to decide between you.” Upon hearing this, off they started. The Crocodile, being used to the water, reached the opposite bank of the river first, and was not long in standing beside the wall. Here he waited till the Elephant came up. The latter, seeing at a glance how matters stood, extended his long trunk, and reached the helmet quite easily. They then made their way together back again across the river. The Elephant, anxious to keep up with the Crocodile in the water, forgot that he was carrying the helmet on his back, and a sudden lurch caused the prize to slip off and sink to the bottom. The Crocodile noticed the accident, so down he dived, and brought it up in his capacious mouth. They then returned, and the Crocodile laid the helmet at the Lion’s feet. His Majesty took up the helmet, and addressing the Elephant, said: “You, on account of your size and trunk, were able to reach the prize on the wall but, having lost it, you were unable to recover it. And you,” said the Lion, turning to the Crocodile, “although unable to reach the helmet, were able to dive for it and save it. You are both wise and clever in your respective ways. Neither is better than the other.”'],
                ['title' => 'Songs of the Witches', 'word_count' => 202, 'text' => 'Round about the cauldron go: Scale of dragon, tooth of wolf, In the poisoned entrails throw. Witch\'s mummy, maw and gulf Toad, that under cold stone Of the ravin\'d salt-sea shark, Days and nights has thirty-one Root of hemlock digg\'d i’ the dark, Sweated venom sleeping got, Liver of blaspheming Jew; Boil thou first i’ the charmed pot. Gall of goat; and slips of yew Double, double toil and trouble; Sliver\'d in the moon\'s eclipse; Fire burn and cauldron bubble. Nose of Turk, and Tartar\'s lips; Fillet of a fenny snake, Finger of birth-strangled babe In the cauldron boil and bake; Ditch-deliver\'d by a drab, Eye of newt and toe of frog, Make the gruel thick and slab: Wool of bat and tongue of dog, Add thereto a tiger\'s chaudron, Adder\'s fork and blind-worm\'s sting, For the ingredients of our cauldron. Lizard\'s leg and owlet\'s wing. Double, double toil and trouble, For a charm of powerful trouble, Fire burn and cauldron bubble. Like a hell-broth boil and bubble. Cool it with a baboon\'s blood, Double, double toil and trouble; Then the charm is firm and good. Fire burn and cauldron bubble. This poem is in the public domain.'],
                ['title' => 'The Boy Who Cried Wolf', 'word_count' => 162, 'text' => 'Aesop Fable There once was a shepherd boy who was bored as he sat on the hillside watching the village sheep. To amuse himself he took a great breath and sang out, "Wolf! Wolf! The Wolf is chasing the sheep!" The villagers came running up the hill to help the boy drive the wolf away. But when they arrived at the top of the hill, they found no wolf. The boy laughed at the sight of their angry faces. "Don\'t cry \'wolf\', shepherd boy," said the villagers, "when there\'s no wolf!" They went grumbling back down the hill. Later, the boy sang out again, "Wolf! Wolf! The wolf is chasing the sheep!" To his naughty delight, he watched the villagers run up the hill to help him drive the wolf away. When the villagers saw no wolf they sternly said, "Save your frightened song for when there is really something wrong! Don\'t cry \'wolf\' when there is NO wolf!"'],
                ['title' => 'The Boy Who Cried Wolf II', 'word_count' => 148, 'text' => 'But the boy just grinned and watched them go grumbling down the hill once more. Later, he saw a REAL wolf prowling about his flock. Alarmed, he leaped to his feet and sang out as loudly as he could, "Wolf! Wolf!" But the villagers thought he was trying to fool them again, and so they didn\'t come. At sunset, everyone wondered why the shepherd boy hadn\'t returned to the village with their sheep. They went up the hill to find the boy. They found him weeping. "There really was a wolf here! The flock has scattered! I cried out, "Wolf!" Why didn\'t you come?" An old man tried to comfort the boy as they walked back to the village. "We\'ll help you look for the lost sheep in the morning," he said, putting his arm around the youth, "Nobody believes a liar...even when he is telling the truth!"'],
                ['title' => 'A Day at the Beach', 'word_count' => 58, 'text' => 'Author: Unknown The sun on my face, the sand in my toes, makes any day a delight. Hunting for seashells, and surfing the waves, makes everything seem alright. Building a castle, fit for a king, makes all my dreams within reach. Wearing my shades and getting a tan, makes a great day at the Beach.'],
                ['title' => 'I Wanna Do Right', 'word_count' => 100, 'text' => 'I wanna do right, wanna do what\'s right I\'m gonna give You all of my life I put my trust in You, Jesus And You\'ll show me, show me how to do right Hey, hey, every word I say Ooh, ooh, I wanna be like You Oh, my, my, every day goes by I wanna be more like You I wanna be more like You Bridge: I was made to give You praise Make me more like You I was made to give You praise Make me more like You In all I do (Repeat Chorus)'],
            ],
            'posttest' => ['title' => 'My First Baseball Game', 'word_count' => 255, 'text' => 'Randy Ryan I remember my first Cubs game. My uncle came to take my sister and me to it. It was a sunny Saturday. He drove all the way from Indiana to get us. Then we took the train to the ballpark. He said it would be hard to find a parking space there, so he didn’t drive there. He was right. When we got there it was so crowded. We had tickets that were for seats far back. It seemed like I climbed about 300 steps to get to them. But when we got there and I turned around I could see everything. I saw the whole field. It was much better than watching it on TV. Then the game started. Everyone cheered. The man next to me said, “This is going to be the year. They are playing really well.” My uncle said to him, “Let’s hope this is the one.” But then he whispered to us, “Jerome and Felicia, we’ll have to wait and see. Remember last year? They started out well and then they lost at the end.” “Hey, Hey, Hey!” The Cub batter hit a ball far to the wall. Just then I heard “Hot dogs!” “Peanuts!” I looked and saw a man with a big tray hanging from his shoulders. It was full of hotdogs in plastic wrap and bags of peanuts. “Three hot dogs,” my uncle shouted. Then he gave the man next to us $6. He passed it to the man with the hot dogs. He sent back three hot dogs. “This is great,” I said to my uncle. “Not so great,” he said. “We just struck out.” While I had been watching the hotdogs, the team had struck out. It went on that way for the rest of the game. We got peanuts. We even got another hot dog. And the Cubs kept losing. We’d all hope every time a batter came to bat. One by one they struck out. Still, everyone was staying happy. Even at the end. The score was 7 to 0. The Cubs never got a run. “Tomorrow, they’ll win,” one person said. “Right. This was just a bad day for them,” another said. “The pitcher tomorrow is really good.” When we were on the way home, I asked my uncle, “Why was everyone so sure they will win next time?” “That’s what it means to be a Cubs fan. We believe in tomorrow. When they win, it’s the best. Every year, we hope. Every game we hope. That’s loyalty. It’s about supporting your team no matter what. Cubs fans are loyal. And it’s about having fun as a family. Did you have fun?” As our uncle was about to drive home to Indiana, Felicia said, “It was great. I see what you meant. Even when they lose, they are like a family, they stick together. Thanks for taking us. And thanks for being loyal to us.”'],
        ],
        5 => [
            'pretest' => ['title' => 'The Crocodile and the Monkey', 'word_count' => 491, 'text' => 'Once upon a time, there lived a monkey on a mango tree on the banks of a river. The mangoes of that tree were the sweetest of all. The tree bore fruits year-round. The monkey used to live very happily on the tree eating the tasty fruits and playing on the tree. On a particular day, a crocodile came near that mango tree. He seemed very exhausted. The monkey offered him some delicious mangoes from the tree. The crocodile loved those mangoes and thanked the monkey for the same. From then on, the crocodile used to visit the monkey every day and they became good friends. One day the crocodile thought to take some mangoes for his wife. When his wife ate the mangoes, she demanded something very absurd from the crocodile. She said that these fruits are so tasty, then how delicious will be the heart of that monkey who regularly eats these mangoes! She ordered the crocodile to bring the monkey’s heart for her. The crocodile was shocked at her demand. The monkey was his friend. How could he betray him? He declined to kill the monkey and bring his heart to her. The crocodile’s wife was adamant about getting the monkey’s heart. She told the crocodile that she is not keeping well and the doctor has recommended her to eat a monkey’s heart to recover. She even threatened him that if the crocodile didn’t get the monkey’s heart for her, she would surely die. The crocodile had to give in to her order. With a heavy heart, the crocodile left to get the monkey. He went to the monkey and said, “Friend, my wife loved the mangoes sent by you. She has invited you to our house to thank you.” The monkey agreed and sat on the crocodile’s back so that the crocodile could take him to his house. In the middle of the river, the crocodile began sinking in. The monkey got frightened and he asked the crocodile as to why he was sinking. The crocodile, knowing that now there was no escape for the monkey, replied, “Forgive me, my friend. My wife needs to eat your heart to save her life. That’s why I am taking you with me.” The monkey was outraged. The monkey was smart. He kept calm and told the crocodile that he would be more than happy to save his wife’s life but he left his heart at the mango tree. The monkey told him that they can quickly go and get his heart from the tree. The crocodile accepted it at once and turned back. As soon as they reached the tree, the monkey jumped onto the tree and said, “O foolish crocodile, how can someone take out his heart and keep it somewhere else? You have deceived me as a friend. Now go and never come back. The ashamed crocodile went back to his home.'],
            'interventions' => [
                ['title' => 'Fight Song', 'word_count' => 332, 'text' => 'Song by Rachel Platten Like a small boat, On the ocean, Sending big waves, Into motion Like how a single word , Can make a heart open I might only have one match, But I can make an explosion And all those things I didn\'t say, Wrecking balls inside my brain I will scream them loud tonight, Can you hear my voice this time? This is my fight song, Take back my life song Prove I\'m alright song, My power\'s turned on Starting right now I\'ll be strong, I\'ll play my fight song And I don\'t really care if nobody else believes \'Cause I\'ve still got a lot of fight left in me Losing friends and I\'m chasing sleep Everybody\'s worried about me In too deep Say I\'m in too deep (in too deep) And it\'s been two years I miss my home But there\'s a fire burning in my bones Still believe. Yeah, I still believe And all those things I didn\'t say Wrecking balls inside my brain I will scream them loud tonight Can you hear my voice this time? This is my fight song, Take back my life song Prove I\'m alright song, My power\'s turned on Starting right now I\'ll be strong, I\'ll play my fight song And I don\'t really care if nobody else believes \'Cause I\'ve still got a lot of fight left in me A lot of fight left in me, Like a small boat On the ocean, Sending big waves Into motion Like how a single word, Can make a heart open I might only have one match But I can make an explosion This is my fight song, Take back my life song Prove I\'m alright song, My power\'s turned on Starting right now I\'ll be strong (I\'ll be strong) I\'ll play my fight song And I don\'t really care if nobody else believes \'Cause I\'ve still got a lot of fight left in me Know I\'ve still got a lot of fight left in me'],
                ['title' => 'You Can', 'word_count' => 112, 'text' => 'If you think you’re beaten, you are… If you think you dare not, you don’t… If you like to win…but think you can’t… It’s almost a cinch, YOU WON’T!! If you think you’ll lose, you’re lost…. For out in the world, you’ll find… Success begins with a fellow’s will…. It’s all in a state of mind. If you think you’re outclassed, you are…. You’ve got to think high to rise… You’ve got to be sure of yourself before…. You can ever win the prize. Life’s battles don’t always go… To the stronger or faster man… But sooner or later the one who wins… IS THE ONE WHO THINKS HE CAN'],
                ['title' => 'Print Your Own Medicine', 'word_count' => 472, 'text' => 'By Lee Cronin Organic chemists make molecules, very complicated molecules, by chopping up a big molecule into small molecules and reverse engineering. And as a chemist, one of the things I wanted to ask my research group a couple of years ago is, could we make a really cool universal chemistry set? In essence, could we "app" chemistry? Now what would this mean, and how would we do it? Well to start to do this, we took a 3D printer and we started to print our beakers and our test tubes on one side and then print the molecule at the same time on the other side and combine them together in what we call reactionware. And so, by printing the vessel and doing the chemistry at the same time, we may start to access this universal toolkit of chemistry. Now what could this mean? Well, if we can embed biological and chemical networks like a search engine, so if you have a cell that\'s ill that you need to cure or bacteria that you want to kill, if you have this embedded in your device at the same time, and you do the chemistry, you may be able to make drugs in a new way. So how are we doing this in the lab? Well, it requires software, it requires hardware and it requires chemical inks. And so the really cool bit is, the idea is that we want to have a universal set of inks that we put out with the printer, and you download the blueprint, the organic chemistry for that molecule and you make it in the device. And so, you can make your molecule in the printer using this software. So, what could this mean? Well, ultimately, it could mean that you could print your own medicine. And this is what we\'re doing in the lab at the moment. But to take baby steps to get there, first of all we want to look at drug design and production, or drug discovery and manufacturing. Because if we can manufacture it after we\'ve discovered it, we could deploy it anywhere. You don\'t need to go to the chemist anymore. We can print drugs at point of need. We can download new diagnostics. Say a new super bug has emerged. You put it in your search engine, and you create the drug to treat the threat. So, this allows you on-the-fly molecular assembly. But perhaps for me the core bit going into the future is this idea of taking your own stem cells, with your genes and your environment, and you print your own personal medicine. And if that doesn\'t seem fanciful enough, where do you think we\'re going to go? Well, you\'re going to have your own personal matter fabricator. Beam me up, Scotty. (Applause)'],
                ['title' => 'When You Are Old', 'word_count' => 104, 'text' => 'William Butler Yeats When you are old and grey and full of sleep, And nodding by the fire, take down this book, And slowly read, and dream of the soft look Your eyes had once, and of their shadows deep; How many loved your moments of glad grace, And loved your beauty with love false or true, But one man loved the pilgrim soul in you, And loved the sorrows of your changing face; And bending down beside the glowing bars, Murmur, a little sadly, how Love fled And paced upon the mountains overhead And hid his face amid a crowd of stars.'],
                ['title' => 'Jimmy Jet and His TV Set', 'word_count' => 150, 'text' => 'Shel Silverstein I\'ll tell you the story of Jimmy Jet-- And you know what I tell you is true. He loved to watch his TV set Almost as much as you. He watched all day, he watched all night Till he grew pale and lean, From "The Early Show" to "The Late Show" And all the shows in between. He watched till his eyes were frozen wide, And his bottom grew into his chair. And his chin turned into a tuning dial, And antennae grew out of his hair. And his brains turned into TV tubes, And his face to a TV screen. And two knobs saying "vert." and "horiz." Grew where his ears had been. And he grew a plug that looked like a tail So we plugged in little Jim. And now instead of him watching TV We all sit around and watch him.'],
                ['title' => 'Pygmalion: Henry and Eliza', 'word_count' => 523, 'text' => 'George Bernard Shaw’s play Pygmalion was the basis for the famous musical My Fair Lad y. First performed in 1913, Pygmalion is the story of Eliza Doolittle, a poor and unsophisticated flower seller on the streets of London, who wants to learn to speak “like a lady.” In this passage from Act I, she has met by chance Professor Henry Higgins, a grumpy professor of phonetics, near a church during a rainstorm. They are amongst a group of people who have gathered under the church’s portico to stay dry. Henry has been listening to the other people as part of his research. Eliza was afraid for a time that he was a policeman trying to arrest her and is just beginning to recover from her fear. Henry is “The Note Taker” below. Eliza is “The Flower Girl,” and “The Gentleman” is Colonel Pickering, who was part of the group. The rain has stopped. The Flower Girl: Poor girl! Hard enough for her to live without being worried and chivied. The Gentleman: [returning to his former place on the note taker’s left] How do you do it, if I may ask? The Note Taker: Simply phonetics. The science of speech. That’s my profession; also my hobby. Happy is the man who can make a living by his hobby! You can spot an Irishman or a Yorkshireman by his brogue. I can place any man within six miles. I can place him within two miles in London. Sometimes within two streets. The Flower Girl: Ought to be ashamed of himself, unmanly coward! The Gentleman: But is there a living in that? The Note Taker: Oh yes. Quite a fat one. This is an age of upstarts. Men begin in Kentish Town with 80 pounds a year, and end in Park Lane with a hundred thousand. They want to drop Kentish Town; but they give themselves away every time they open their mouths. Now I can teach them— The Flower Girl: Let him mind his own business and leave a poor girl— The Note Taker: [explosively] Woman: cease this detestable boohooing instantly; or else seek the shelter of some other lace of worship. The Flower Girl: [with feeble defiance] I’ve a right to be here if I like, same as you. The Note Taker: A woman who utters such depressing and disgusting sounds has no right to be anywhere—no right to live. Remember that you are a human being with a soul and the divine gift of articulate speech: that your native language is the language of Shakespeare and Milton and The Bible; and don’t sit there crooning like a bilious pigeon. The Flower Girl: [quite overwhelmed, and looking up at him in mingled wonder and deprecation without daring to raise her head] Ah—ah—ah—ow—ow—oo! The Note Taker: [whipping out his book] Heavens! what a sound! [He writes; then holds out the book and reads, reproducing her vowels exactly] Ah—ah—ah—ow—ow— ow—oo! The Flower Girl: [tickled by the performance, and laughing in spite of herself] Garn!'],
                ['title' => 'Old McDonald Had a Farm', 'word_count' => 190, 'text' => 'Old MacDonald had a farm, E-I-E-I-O. And on that farm he had a cow, E-I-E-I-O. With a moo here and a moo there, here a moo, there a moo, everywhere a moo-moo. Old MacDonald had a farm, E-I-E-I-O. Old MacDonald had a farm, E-I-E-I-O. And on that farm he had a chicken, E-I-E-I-O. With a cluck here and a cluck there, here a cluck, there a cluck, everywhere a cluck-cluck. Old MacDonald had a farm, E-I-E-I-O. Old MacDonald had a farm, E-I-E-I-O. And on that farm he had a duck, E-I-E-I-O. With a quack here and a quack there, here a quack, there a quack, everywhere a quack-quack. Old MacDonald had a farm, E-I-E-I-O. Old MacDonald had a farm, E-I-E-I-O. And on that farm he had a sheep, E-I-E-I-O. With a baa here and a baa there, here a baa, there a baa, everywhere a baa-baa. Old MacDonald had a farm, E-I-E-I-O. Old MacDonald had a farm, E-I-E-I-O. And on that farm he had a pig, E-I-E-I-O. With a oink here and a oink there, here a oink, there a oink, everywhere a oink-oink. Old MacDonald had a farm, E-I-E-I-O.'],
                ['title' => 'The Crocodile and the Monkey', 'word_count' => 495, 'text' => 'Once upon a time, there lived a monkey on a mango tree on the banks of a river. The mangoes of that tree were the sweetest of all. The tree bore fruits year-round. The monkey used to live very happily on the tree eating the tasty fruits and playing on the tree. On a particular day, a crocodile came near that mango tree. He seemed very exhausted. The monkey offered him some delicious mangoes from the tree. The crocodile loved those mangoes and thanked the monkey for the same. From then on, the crocodile used to visit the monkey every day and they became good friends. One day the crocodile thought to take some mangoes for his wife. When his wife ate the mangoes, she demanded something very absurd from the crocodile. She said that these fruits are so tasty, then how delicious will be the heart of that monkey who regularly eats these mangoes! She ordered the crocodile to bring the monkey’s heart for her. The crocodile was shocked at her demand. The monkey was his friend. How could he betray him? He declined to kill the monkey and bring his heart to her. The crocodile’s wife was adamant about getting the monkey’s heart. She told the crocodile that she is not keeping well and the doctor has recommended her to eat a monkey’s heart to recover. She even threatened him that if the crocodile didn’t get the monkey’s heart for her, she would surely die. The crocodile had to give in to her order. With a heavy heart, the crocodile left to get the monkey. He went to the monkey and said, “Friend, my wife loved the mangoes sent by you. She has invited you to our house to thank you.” The monkey agreed and sat on the crocodile’s back so that the crocodile could take him to his house. In the middle of the river, the crocodile began sinking in. The monkey got frightened and he asked the crocodile as to why he was sinking. The crocodile, knowing that now there was no escape for the monkey, replied, “Forgive me, my friend. My wife needs to eat your heart to save her life. That’s why I am taking you with me.” The monkey was outraged. The monkey was smart. He kept calm and told the crocodile that he would be more than happy to save his wife’s life but he left his heart at the mango tree. The monkey told him that they can quickly go and get his heart from the tree. The crocodile accepted it at once and turned back. As soon as they reached the tree, the monkey jumped onto the tree and said, “O foolish crocodile, how can someone take out his heart and keep it somewhere else? You have deceived me as a friend. Now go and never come back. The ashamed crocodile went back to his home.'],
            ],
            'posttest' => ['title' => 'The Crocodile and the Monkey', 'word_count' => 491, 'text' => 'Post test Passage 16 Once upon a time, there lived a monkey on a mango tree on the banks of a river. The mangoes of that tree were the sweetest of all. The tree bore fruits year-round. The monkey used to live very happily on the tree eating the tasty fruits and playing on the tree. On a particular day, a crocodile came near that mango tree. He seemed very exhausted. The monkey offered him some delicious mangoes from the tree. The crocodile loved those mangoes and thanked the monkey for the same. From then on, the crocodile used to visit the monkey every day and they became good friends. One day the crocodile thought to take some mangoes for his wife. When his wife ate the mangoes, she demanded something very absurd from the crocodile. She said that these fruits are so tasty, then how delicious will be the heart of that monkey who regularly eats these mangoes! She ordered the crocodile to bring the monkey’s heart for her. The crocodile was shocked at her demand. The monkey was his friend. How could he betray him? He declined to kill the monkey and bring his heart to her. The crocodile’s wife was adamant about getting the monkey’s heart. She told the crocodile that she is not keeping well and the doctor has recommended her to eat a monkey’s heart to recover. She even threatened him that if the crocodile didn’t get the monkey’s heart for her, she would surely die. The crocodile had to give in to her order. With a heavy heart, the crocodile left to get the monkey. He went to the monkey and said, “Friend, my wife loved the mangoes sent by you. She has invited you to our house to thank you.” The monkey agreed and sat on the crocodile’s back so that the crocodile could take him to his house. In the middle of the river, the crocodile began sinking in. The monkey got frightened and he asked the crocodile as to why he was sinking. The crocodile, knowing that now there was no escape for the monkey, replied, “Forgive me, my friend. My wife needs to eat your heart to save her life. That’s why I am taking you with me.” The monkey was outraged. The monkey was smart. He kept calm and told the crocodile that he would be more than happy to save his wife’s life but he left his heart at the mango tree. The monkey told him that they can quickly go and get his heart from the tree. The crocodile accepted it at once and turned back. As soon as they reached the tree, the monkey jumped onto the tree and said, “O foolish crocodile, how can someone take out his heart and keep it somewhere else? You have deceived me as a friend. Now go and never come back. The ashamed crocodile went back to his home.'],
        ],
        6 => [
            'pretest' => ['title' => '"Bad Girl"', 'word_count' => 269, 'text' => '"Bad Girl" Hey! Everybody seems to be staring at me.. You! You! All of you! How dare you to stare at me? Why? Is it because I\'m a bad girl? A bad girl I am, A good for nothing teenager, a problem child? That\'s what you call me! I smoke. I drink. I gamble at my young tender age. I lie. I cheat, and I could even kill, If I have too. Yes, I\'m a bad girl, but where are my parents? You! You! You are my good parents? My good elder brother and sister in this society where I live? Look…look at me…What have you done to me? You have pampered and spoiled me, neglected me when I needed you most! Entrusted me to a yaya, whose intelligence was much lower than mine! While you go about your parties, your meetings and gambling session… Thus… I drifted away from you! Longing for a father\'s love, yearning for a mother\'s care! As I grew up, everything changed! You too have changed! You spent more time in your poker, mahjong tables, bars and night clubs. You even landed on the headlines of the newspaper as crooks, peddlers and you racketeers. Now, you call me names, accuse me of everything I do to myself? Tell me! How good are you? If you really wish to ensure my future… Then hurry….hurry back home! Where I await you, because I need you… Protect me from all evil influences that will threaten at my very own understanding… But if I am bad, really bad…then, you\'ve got to help me! Help me! Oh please…Help me.'],
            'interventions' => [
                ['title' => 'It is Raining', 'word_count' => 241, 'text' => 'Where would you like to be in the rain? Where would you like to be? I’d like to be on a city street Where the rain comes driving down Trying to make things neat As it washes the houses, roof and wall The taxis, buses, cars, and all. That’s where I’d like to be in the rain That’s where I’d like to be. It is raining. Where would you like to be in the rain? Where would you like to be? I’d like to be in a tall tree top Where the rain comes dripping drop, drop, drop, drop, Around on every side – where it wets the farmers, the barns, the pig. the cows, the chickens, both little and big. Where it batters and beats on a field of grain. And makes the little birds hide from the rain. That’s where I’d like to be in the rain. That’s where I’d like to be. It is raining. Where would you like to be in the rain? Where would you like to be? I’d like to be on a ship at sea Where everything’s wet as can be And the waves are rolling high Where sailors are pulling the ropes and singing And winds in the rigging and salt’s sprays stinging And round us sea gulls cry On a dipping, skimming ship at sea. That’s where I’d like to be in the rain. That’s where I’d like to be.'],
                ['title' => 'You Learn', 'word_count' => 220, 'text' => 'Song by Alanis Morissette I recommend getting your heart trampled on to anyone I recommend walking around naked in your living room Swallow it down (what a jagged little pill) It feels so good (swimming in your stomach) Wait until the dust settles You live you learn, You love you learn You cry you learn, You lose you learn You bleed you learn, You scream you learn I recommend biting off more than you can chew to anyone certainly do I recommend sticking your foot in your mouth at anytime Feel free Throw it down (the caution blocks you from the wind) Hold it up (to the rays) You wait and see when the smoke clears You live you learn, You love you learn You cry you learn, You lose you learn You bleed you learn, You scream you learn Wear it out (like a three-year-old would do) Melt it down (you\'re gonna have to eventually anyway) The fire trucks are coming up around the bend You live you learn, You love you learn You cry you learn, You lose you learn You bleed you learn, You scream you learn You grieve you learn, You choke you learn You laugh you learn, You choose you learn You pray you learn, You ask you learn You live you learn'],
                ['title' => 'The House on the Hill', 'word_count' => 107, 'text' => 'They are all gone away, The House is shut and still, There is nothing more to say. Through broken walls and gray The winds blow bleak and shrill: They are all gone away. Nor is there one to-day, To speak them good or ill: There is nothing more to say. Why is it then we stray, Around the sunken sill? They are all gone away, And our poor fancy-play, For them is wasted skill: There is nothing more to say. There is ruin and decay, In the House on the Hill: They are all gone away, There is nothing more to say.'],
                ['title' => 'The Golden Egg', 'word_count' => 218, 'text' => 'Once upon a time, there lived a cloth merchant in a village with his wife and two children. They were indeed quite well-off. They had a beautiful hen which laid an egg every day. It was not an ordinary egg, rather, a golden egg. But the man was not satisfied with what he used to get daily. He was a get rich-trice kind of a person. The man wanted to get all the golden eggs from his hen at one single go. So, one day he thought hard and at last clicked upon a plan. He decided to kill the hen and get all the eggs together. So, the next day when the hen laid a golden egg, the man caught hold of it, took a sharp knife, chopped off its neck and cut its body open. There was nothing but blood all around & no trace of any egg at all. He was highly grieved because now he would not get even one single egg. His life was going on smoothly with one egg a day but now, he himself made his life miserable. The outcome of his greed was that he started becoming poorer & poorer day by day and ultimately became a pauper. How jinxed and how much foolish he was.'],
                ['title' => 'To the River', 'word_count' => 78, 'text' => 'Edgar Allan Poe - 1809-1849 Fair river! in thy bright, clear flow Of crystal, wandering water, Thou art an emblem of the glow Of beauty—the unhidden heart— The playful maziness of art In old Alberto’s daughter; But when within thy wave she looks— Which glistens then, and trembles— Why, then, the prettiest of brooks Her worshipper resembles; For in my heart, as in thy stream, Her image deeply lies— His heart which trembles at the beam Of her soul-searching eyes.'],
                ['title' => 'Be Glad Your Nose is on Your Face', 'word_count' => 140, 'text' => 'By Jack Prelutsky Be glad your nose is on your face, not pasted on some other place, for if it were where it is not, you might dislike your nose a lot. Imagine if your precious nose, were sandwiched in between your toes, that clearly would not be a treat, for you\'d be forced to smell your feet. Your nose would be a source of dread were it attached atop your head, it soon would drive you to despair, forever tickled by your hair. Within your ear, your nose would be an absolute catastrophe, for when you were obliged to sneeze, your brain would rattle from the breeze. Your nose, instead, through thick and thin, remains between your eyes and chin, not pasted on some other place-- be glad your nose is on your face.'],
                ['title' => 'The Crocodile and the Monkey', 'word_count' => 435, 'text' => 'Once upon a time, there lived a monkey on a mango tree on the banks of a river. The mangoes of that tree were the sweetest of all. The tree bore fruits year-round. The monkey used to live very happily on the tree eating the tasty fruits and playing on the tree. On a particular day, a crocodile came near that mango tree. He seemed very exhausted. The monkey offered him some delicious mangoes from the tree. The crocodile loved those mangoes and thanked the monkey for the same. From then on, the crocodile used to visit the monkey every day and they became good friends. One day the crocodile thought to take some mangoes for his wife. When his wife ate the mangoes, she demanded something very absurd from the crocodile. She said that these fruits are so tasty, then how delicious will be the heart of that monkey who regularly eats these mangoes! She ordered the crocodile to bring the monkey’s heart for her. The crocodile was shocked at her demand. The monkey was his friend. How could he betray him? He declined to kill the monkey and bring his heart to her. The crocodile’s wife was adamant about getting the monkey’s heart. She told the crocodile that she is not keeping well and the doctor has recommended her to eat a monkey’s heart to recover. She even threatened him that if the crocodile didn’t get the monkey’s heart for her, she would surely die. The crocodile had to give in to her order. With a heavy heart, the crocodile left to get the monkey. He went to the monkey and said, “Friend, my wife loved the mangoes sent by you. She has invited you to our house to thank you.” The monkey agreed and sat on the crocodile’s back so that the crocodile could take him to his house. In the middle of the river, the crocodile began sinking in. The monkey got frightened and he asked the crocodile as to why he was sinking. The crocodile, knowing that now there was no escape for the monkey, replied, “Forgive me, my friend. My wife needs to eat your heart to save her life. That’s why I am taking you with me.” The monkey was outraged. The monkey was smart. He kept calm and told the crocodile that he would be more than happy to save his wife’s life but he left his heart at the mango tree. The monkey told him that they can quickly go and get his heart from the tree. The crocodile accepted it at once and turned back. As soon as they reached the tree, the monkey jumped onto the tree and said, “O foolish crocodile, how can someone take out his heart and keep it somewhere else? You have deceived me as a friend. Now go and never come back. The ashamed crocodile went back to his home.'],
                ['title' => 'Pygmalion: Henry and Eliza', 'word_count' => 522, 'text' => 'George Bernard Shaw’s play Pygmalion was the basis for the famous musical My Fair Lady. First performed in 1913, Pygmalion is the story of Eliza Doolittle, a poor and unsophisticated flower seller on the streets of London, who wants to learn to speak “like a lady.” In this passage from Act I, she has met by chance Professor Henry Higgins, a grumpy professor of phonetics, near a church during a rainstorm. They are amongst a group of people who have gathered under the church’s portico to stay dry. Henry has been listening to the other people as part of his research. Eliza was afraid for a time that he was a policeman trying to arrest her and is just beginning to recover from her fear. Henry is “The Note Taker” below. Eliza is “The Flower Girl,” and “The Gentleman” is Colonel Pickering, who was part of the group. The rain has stopped. The Flower Girl: Poor girl! Hard enough for her to live without being worried and chivied. The Gentleman: [returning to his former place on the note taker’s left] How do you do it, if I may ask? The Note Taker: Simply phonetics. The science of speech. That’s my profession; also my hobby. Happy is the man who can make a living by his hobby! You can spot an Irishman or a Yorkshireman by his brogue. I can place any man within six miles. I can place him within two miles in London. Sometimes within two streets. The Flower Girl: Ought to be ashamed of himself, unmanly coward! The Gentleman: But is there a living in that? The Note Taker: Oh yes. Quite a fat one. This is an age of upstarts. Men begin in Kentish Town with 80 pounds a year, and end in Park Lane with a hundred thousand. They want to drop Kentish Town; but they give themselves away every time they open their mouths. Now I can teach them— The Flower Girl: Let him mind his own business and leave a poor girl— The Note Taker: [explosively] Woman: cease this detestable boohooing instantly; or else seek the shelter of some other place of worship. The Flower Girl: [with feeble defiance] I’ve a right to be here if I like, same as you. The Note Taker: A woman who utters such depressing and disgusting sounds has no right to be anywhere—no right to live. Remember that you are a human being with a soul and the divine gift of articulate speech: that your native language is the language of Shakespeare and Milton and The Bible; and don’t sit there crooning like a bilious pigeon. The Flower Girl: [quite overwhelmed, and looking up at him in mingled wonder and deprecation without daring to raise her head] Ah—ah—ah—ow—ow—oo! The Note Taker: [whipping out his book] Heavens! what a sound! [He writes; then holds out the book and reads, reproducing her vowels exactly] Ah—ah—ah—ow—ow— ow—oo! The Flower Girl: [tickled by the performance, and laughing in spite of herself] Garn!'],
                ['title' => 'My First Baseball Game', 'word_count' => 257, 'text' => 'Randy Ryan I remember my first Cubs game. My uncle came to take my sister and me to it. It was a sunny Saturday. He drove all the way from Indiana to get us. Then we took the train to the ballpark. He said it would be hard to find a parking space there, so he didn’t drive there. He was right. When we got there it was so crowded. We had tickets that were for seats far back. It seemed like I climbed about 300 steps to get to them. But when we got there and I turned around I could see everything. I saw the whole field. It was much better than watching it on TV. Then the game started. Everyone cheered. The man next to me said, “This is going to be the year. They are playing really well.” My uncle said to him, “Let’s hope this is the one.” But then he whispered to us, “Jerome and Felicia, we’ll have to wait and see. Remember last year? They started out well and then they lost at the end.” “Hey, Hey, Hey!” wall. NBggSfQ= Just then I heard “Hot dogs!” “Peanuts!” I looked and saw a man with a big tray hanging from his shoulders. It was full of hotdogs in plastic wrap and bags of peanuts. “Three hot dogs,” my uncle shouted. Then he gave the man next to us $6. He passed it to the man with the hot dogs. (257 Words)'],
            ],
            'posttest' => ['title' => '"Bad Girl"', 'word_count' => 269, 'text' => 'Posttest Passage 17 "Bad Girl" Hey! Everybody seems to be staring at me.. You! You! All of you! How dare you to stare at me? Why? Is it because I\'m a bad girl? A bad girl I am, A good for nothing teen ager, a problem child? That\'s what you call me! I smoke. I drink. I gamble at my young tender age. I lie. I cheat, and I could even kill, If I have too. Yes, I\'m a bad girl, but where are my parents? You! You! You are my good parents? My good elder brother and sister in this society where I live? Look…look at me…What have you done to me? You have pampered and spoiled me,neglected me when I needed you most! Entrusted me to a yaya, whose intelligence was much lower than mine! While you go about your parties, your meetings and gambling session… Thus… I drifted away from you! Longing for a father\'s love, yearning for a mother\'s care! As I grew up, everything changed! You too have changed! You spent more time in your poker, mahjong tables, bars and night clubs. You even landed on the headlines of the newspaper as crooks, peddlers and you racketeers. Now, you call me names, accuse me of everything I do to myself? Tell me! How good are you? If you really wish to ensure my future… Then hurry….hurry back home! Where I await you, because I need you… Protect me from all evil influences that will threaten at my very own understanding… But if I am bad, really bad…then, you\'ve got to help me! Help me! Oh please…Help me'],
        ],
    ];
}
